export const counties = [
    { label: 'Mombasa', value: 'Mombasa' },
    { label: 'Kwale', value: 'Kwale' },
    { label: 'Kilifi', value: 'Kilifi' },
    { label: 'Tana River', value: 'Tana River' },
    { label: 'Lamu', value: 'Lamu' },
    { label: 'Taita-Taveta', value: 'Taita-Taveta' },
    { label: 'Garissa', value: 'Garissa' },
    { label: 'Wajir', value: 'Wajir' },
    { label: 'Mandera', value: 'Mandera' },
    { label: 'Marsabit', value: 'Marsabit' },
    { label: 'Isiolo', value: 'Isiolo' },
    { label: 'Meru', value: 'Meru' },
    { label: 'Tharaka-Nithi', value: 'Tharaka-Nithi' },
    { label: 'Embu', value: 'Embu' },
    { label: 'Kitui', value: 'Kitui' },
    { label: 'Machakos', value: 'Machakos' },
    { label: 'Makueni', value: 'Makueni' },
    { label: 'Nyandarua', value: 'Nyandarua' },
    { label: 'Nyeri', value: 'Nyeri' },
    { label: 'Kirinyaga', value: 'Kirinyaga' },
    { label: 'Murang\'a', value: 'Murang\'a' },
    { label: 'Kiambu', value: 'Kiambu' },
    { label: 'Turkana', value: 'Turkana' },
    { label: 'West Pokot', value: 'West Pokot' },
    { label: 'Samburu', value: 'Samburu' },
    { label: 'Trans-Nzoia', value: 'Trans-Nzoia' },
    { label: 'Uasin Gishu', value: 'Uasin Gishu' },
    { label: 'Elgeyo-Marakwet', value: 'Elgeyo-Marakwet' },
    { label: 'Nandi', value: 'Nandi' },
    { label: 'Baringo', value: 'Baringo' },
    { label: 'Laikipia', value: 'Laikipia' },
    { label: 'Nakuru', value: 'Nakuru' },
    { label: 'Narok', value: 'Narok' },
    { label: 'Kajiado', value: 'Kajiado' },
    { label: 'Kericho', value: 'Kericho' },
    { label: 'Bomet', value: 'Bomet' },
    { label: 'Kakamega', value: 'Kakamega' },
    { label: 'Vihiga', value: 'Vihiga' },
    { label: 'Bungoma', value: 'Bungoma' },
    { label: 'Busia', value: 'Busia' },
    { label: 'Siaya', value: 'Siaya' },
    { label: 'Kisumu', value: 'Kisumu' },
    { label: 'Homa Bay', value: 'Homa Bay' },
    { label: 'Migori', value: 'Migori' },
    { label: 'Kisii', value: 'Kisii' },
    { label: 'Nyamira', value: 'Nyamira' },
    { label: 'Nairobi', value: 'Nairobi' }
];

export  const water = [
    { label: 'Rain', value: 'Rain' },
    { label: 'Irrigation', value: 'Irrigation' },
  ];

export const crop = [
    { label: 'Maize', value: 'Maize' },
    { label: 'Tea', value: 'Tea' },
    { label: 'Coffee', value: 'Coffee' },
    { label: 'Sugarcane', value: 'Sugarcane' },
    { label: 'Wheat', value: 'Wheat' },
    { label: 'Rice', value: 'Rice' },
    { label: 'Sorghum', value: 'Sorghum' },
    { label: 'Potatoes', value: 'Potatoes' },
    { label: 'Bananas', value: 'Bananas' }
];

